spring.application.name=Backend_study
server.port=8081

# H2 In-Memory Datenbank
spring.datasource.url=jdbc:h2:mem:shopdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# CORS for frontend on port 8080 and 5173
cors.allowed-origins=http://localhost:8080,http://localhost:5173
